"""Bilingual deterministic reports for the Stage 6 product branches."""

from __future__ import annotations

from html import escape
from typing import Any


def _value(value: Any, digits: int = 3) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def _page(
    *,
    title: str,
    subtitle: str,
    run_id: str,
    created_at: str,
    status: str,
    ruleset_id: str,
    metrics: list[tuple[str, str]],
    notice: str,
    body: str,
    actions: list[dict[str, Any]],
) -> str:
    cards = "".join(
        f"<div class='metric'><b>{escape(value)}</b><span>{escape(label)}</span></div>"
        for value, label in metrics
    )
    action_rows = "".join(
        "<tr>"
        f"<td><code>{escape(str(action['action_id']))}</code></td>"
        f"<td>{escape(str(action['question']))}<span>{escape(str(action.get('question_zh', '')))}</span></td>"
        f"<td>{escape(str(action['status']))}</td>"
        "</tr>"
        for action in actions
    )
    return f"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title><style>
:root {{--ink:#17211d;--muted:#5d6963;--line:#d8dedb;--paper:#fff;--wash:#f4f7f5;--green:#16633d;--amber:#9a5b00;}}
*{{box-sizing:border-box}}body{{margin:0;color:var(--ink);background:var(--wash);font-family:Arial,"Noto Sans SC","Microsoft YaHei",sans-serif;line-height:1.55}}
header{{background:#17352a;color:#fff;padding:32px 24px}}header div,main{{max-width:1180px;margin:auto}}h1{{margin:0 0 7px;font-size:29px;letter-spacing:0}}h2{{margin:30px 0 11px;font-size:20px}}
main{{padding:22px 22px 50px}}.meta{{color:#ccdad3;font-size:12px}}.summary{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}}
.metric{{background:#fff;border:1px solid var(--line);border-radius:6px;padding:14px}}.metric b{{display:block;color:var(--green);font-size:24px}}.metric span,td span{{display:block;color:var(--muted);font-size:12px}}
.notice{{margin:14px 0;padding:12px 14px;border-left:4px solid var(--amber);background:#fff8e8}}.table-wrap{{overflow:auto;border:1px solid var(--line);border-radius:6px;background:#fff}}
table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{padding:9px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{background:#edf2ef;white-space:nowrap}}
.req{{background:#fff;border:1px solid var(--line);border-radius:6px;padding:12px 14px;margin:8px 0}}code{{font-size:12px}}footer{{margin-top:30px;color:var(--muted);font-size:12px}}
@media(max-width:760px){{.summary{{grid-template-columns:1fr 1fr}}main{{padding:16px 11px 38px}}header{{padding:25px 15px}}}}
</style></head><body><header><div><h1>{escape(title)}</h1><p>{escape(subtitle)}</p><p class="meta">Run {escape(run_id)} · {escape(created_at)} · status={escape(status)} · {escape(ruleset_id)}</p></div></header>
<main><section class="summary">{cards}</section><div class="notice">{escape(notice)}</div>{body}
<h2>Human actions / 人工事项</h2><div class="table-wrap"><table><thead><tr><th>Action</th><th>Question / 问题</th><th>Status</th></tr></thead><tbody>{action_rows}</tbody></table></div>
<footer>Generated by versioned deterministic code. Drafts are not synthesis releases and no LLM-authored scientific conclusion is embedded. / 由版本化确定性代码生成；草案不是合成放行文件，且不嵌入 LLM 编写的科学结论。</footer></main></body></html>"""


def _requirements(result: dict[str, Any]) -> str:
    return "".join(
        f"<div class='req'><code>{escape(item['requirement_id'])}</code><br>{escape(item['description'])}</div>"
        for item in result["requirements"]
    ) or "<div class='req'>No missing requirement / 无缺失要求</div>"


def render_protein_product_report(
    result: dict[str, Any],
    actions: list[dict[str, Any]],
    run_id: str,
    created_at: str,
) -> str:
    rows = "".join(
        "<tr>"
        f"<td><b>{escape(product['candidate_key'])}</b><span>{escape(product['design_id'])}</span></td>"
        f"<td>{len(product['antigen_sequence'])}</td><td>{len(product['expression_sequence'])}</td>"
        f"<td>{len(product['elements'])}</td><td>{escape(product['coding_source'])}</td>"
        f"<td>{'yes / 是' if product['translation_verified'] else 'no / 否'}</td>"
        f"<td>{'required / 需要' if product['requires_structure_recheck'] else 'unchanged / 未改变'}</td>"
        "</tr>"
        for product in result["products"]
    )
    body = (
        "<h2>Exact product constructs / 精确产品构建体</h2><div class='table-wrap'><table><thead><tr>"
        "<th>Candidate / 候选</th><th>Antigen aa / 抗原</th><th>Expression aa / 表达构建</th>"
        "<th>Additions / 附加元件</th><th>CDS source / 来源</th><th>Translation / 翻译</th><th>Structure recheck / 结构复核</th>"
        f"</tr></thead><tbody>{rows}</tbody></table></div><h2>Missing requirements / 缺失要求</h2>{_requirements(result)}"
    )
    return _page(
        title="Stage 6A · Recombinant protein product design",
        subtitle="重组蛋白产品设计 · antigen, expression construct, and final product remain separate",
        run_id=run_id,
        created_at=created_at,
        status=result["status"],
        ruleset_id=result["ruleset_id"],
        metrics=[
            (str(len(result["products"])), "Products / 产品"),
            (str(sum(bool(item["elements"]) for item in result["products"])), "Modified constructs / 改造构建"),
            (str(sum(item["translation_verified"] for item in result["products"])), "Verified CDS / 已验证 CDS"),
            (str(len(result["requirements"])), "Missing requirements / 缺失要求"),
        ],
        notice="An exact construct specification is not evidence of expression, purification yield, stability, or efficacy. / 精确构建体定义不等于表达、纯化产率、稳定性或有效性证据。",
        body=body,
        actions=actions,
    )


def render_mrna_product_report(
    result: dict[str, Any],
    actions: list[dict[str, Any]],
    run_id: str,
    created_at: str,
) -> str:
    rows = "".join(
        "<tr>"
        f"<td><b>{escape(design['candidate_key'])}</b><span>{escape(design['design_id'])}</span></td>"
        f"<td>{escape(design['design_type'])}</td><td>{_value(design['metrics']['cai_proxy'])}</td>"
        f"<td>{_value(design['metrics']['gc_fraction'])}</td><td>{design['metrics']['longest_homopolymer']}</td>"
        f"<td>{'yes / 是' if design['translation_verified'] else 'no / 否'}</td>"
        f"<td>{'full / 完整' if design['full_mrna_sequence'] else 'coding only / 仅编码区'}</td>"
        "</tr>"
        for design in result["designs"]
    )
    body = (
        "<h2>Audited coding designs / 已审计编码设计</h2><div class='table-wrap'><table><thead><tr>"
        "<th>Candidate / 候选</th><th>Type / 类型</th><th>CAI proxy</th><th>GC</th>"
        "<th>Longest homopolymer / 最长同聚物</th><th>Translation / 翻译</th><th>Construct / 构建体</th>"
        f"</tr></thead><tbody>{rows}</tbody></table></div><h2>Missing requirements / 缺失要求</h2>{_requirements(result)}"
    )
    return _page(
        title="Stage 6B · mRNA product design",
        subtitle="mRNA 产品设计 · synonymous controls, constraints, Pareto designs, and exact translation audits",
        run_id=run_id,
        created_at=created_at,
        status=result["status"],
        ruleset_id=result["ruleset_id"],
        metrics=[
            (str(len(result["designs"])), "Audited designs / 已审计设计"),
            (str(sum(item["design_type"] != "source_cds_control" for item in result["designs"])), "Synonymous designs / 同义设计"),
            (str(len(result["rejected_designs"])), "Rejected trials / 拒绝试验"),
            (str(len(result["requirements"])), "Missing requirements / 缺失要求"),
        ],
        notice="Language-model or codon scores cannot replace translation identity, hard constraints, licensed non-coding elements, or experimental validation. / 语言模型或密码子评分不能替代翻译一致性、硬约束、获准的非编码元件和实验验证。",
        body=body,
        actions=actions,
    )
